### ISSUE TITLE
Make .pkg file

### ISSUE THREAD

**Issue by Shiloasi** [willowtreeapps/rokul-runnings#46]
HI,
a really useful library I really liked it.
Is there a way to also generate PKG file from JS script?

**Comment by aaron-goff** [comment]
I'm not entirely sure... what's the use case here @Shiloasi ?

**Comment by Shiloasi** [comment]
I`m trying to build Roku auto builder script, so I`m trying to understand if I can use your script for automating the converting of Roku channel source code from ZIP to pkg file.

**Comment by aaron-goff** [comment]
This library is for automating testing and communication between a library and the Roku.

Adding a tool to convert your ZIP to PKG for submission to Roku is out of scope of this library. AFAIK there are a few tools that automate this conversion. I'd recommend checking out @slheavner's library of tools: https://github.com/slheavner/awesome-roku
